---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitea
commonLabels:
  app.kubernetes.io/part-of: gitea

resources:
  - k8s/namespace.yml
  - k8s/gitea.yml
  - k8s/postgres.yml

images:
  - name: docker.io/gitea/gitea
    newTag: "1.14.6"
  - name: docker.io/postgres
    newTag: "13"

configMapGenerator:
  - name: gitea
    envs:
      - config/gitea.env
  - name: gitea-postgres
    envs:
      - config/gitea-postgres.env

secretGenerator:
  - name: gitea
  - name: gitea-postgres
    envs:
      - config/gitea-postgres.secret.env
