---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-postgres
  labels:
    app.kubernetes.io/component: database
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/component: database
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gitea-postgres-data
      containers:
        - name: postgres
          image: docker.io/postgres
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: gitea-postgres
            - secretRef:
                name: gitea-postgres
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
          ports:
            - name: postgres
              containerPort: 5432
          readinessProbe:
            tcpSocket:
              port: postgres
          livenessProbe:
            tcpSocket:
              port: postgres


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-postgres-data
  labels:
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G



---
apiVersion: v1
kind: Service
metadata:
  name: gitea-postgres
  labels:
    app.kubernetes.io/component: database
spec:
  selector:
    app.kubernetes.io/component: database
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
